spring.application.name=spring-security

spring.datasoruce.url=jdbc:hsqldb:mem:testdb
spring.datasource.username=SA
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver


#security configuration

spring.security.user.name=raghureddy
spring.security.user.password=raghureddy
