spring.application.name=spring-security

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Raghu@6633
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# THIS is critical in Boot 4
#spring.h2.console.settings.web-allow-others=true

#security configuration

#spring.security.user.name=raghureddy
#spring.security.user.password=raghureddy
