spring.application.name=spring-security

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Raghu@6633
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
logging.level.org.springframework.security=DEBUG

# THIS is critical in Boot 4
#spring.h2.console.settings.web-allow-others=true
jwt.security.secretkey=ODJweGtzZjJlMW42Mmxic2htZHZwd3B0cnpqdDBkMW12dzQ3NTByaWFweHQ4OTNiaWlvOWR5NmlnbmdkbG91N3Y4MndrbGFmdno4cWI0eTNjbnZyZGphb3oyajgyeGJjam9lNDU4a3I5cDJ6bHl1aTNtZ3dqZmFzczZkYzhqang=
jwt.security.expirytime=30000

#security configuration

#spring.security.user.name=raghureddy
#spring.security.user.password=raghureddy
